collection: '/db/projects/gregorovius/data-sync'
xslt: True

entities:
  letters:
    xpath: '//*:TEI[@*:doctype="letter_fgbe"]'
    search_index:
      text: 
      - qname: "tei:text"
        inline-qname: "tei:ex"
      - qname: "tei:p"
        inline-qname: "tei:ex"
    properties:
      title:
        xpath: ['.//titleStmt/title']
      sender:
        xpath: [
          './/correspAction[@type="sent"]/persName',
          './/correspAction[@type="sent"]/orgName'
        ]
        attrib: ['key']
        multiple: True
      recipient:
        xpath: [
          './/correspAction[@type="received"]/persName',
          './/correspAction[@type="received"]/orgName'
        ]
        attrib: ['key']
        multiple: True
      date:
        xpath: ['.//correspAction[@type="sent"]/date']
        attrib: ['when', 'notBefore', 'from', 'notAfter']
      place:
        properties:
          sent:
            xpath: ['.//correspAction[@type="sent"]/placeName']
            attrib: ['key']
          received:
            xpath: ['.//correspAction[@type="received"]/placeName']
            attrib: ['key']
        attrib: ['key']
      incipit:
        xpath: ['.//body//p[1]']
        filter: 'get_substring_100'
      resp:
        xpath: ['.//titleStmt//persName/surname']
        multiple: True
      mentioned:
        properties:
          persons:
            xpath: ['.//body//persName', './/body//orgName']
            attrib: ['key']
            multiple: True
          places:
            xpath: ['.//body//placeName']
            attrib: ['key']
            multiple: True
          works:
            xpath: ['.//body//bibl']
            attrib: ['corresp', 'sameAs']
            multiple: True

  persons:
    xpath: '//*:TEI[@*:doctype="register"]//(*:person|*:org)'
    properties: 
      type:
        xpath: ['.']
        filter: 'get_node_name'
      name:
        properties:
          surname:
            xpath: ['./persName[@type="reg"]/surname']
          forename:
            xpath: ['./persName[@type="reg"]/forename']
          simpleName:
            xpath: ['./persName[@type="reg"]/name']
          roleName:
            xpath: ['./persName[@type="reg"]/roleName']
          orgName:
            xpath: ['./orgName']
          fullName:
            xpath: ['./persName[@type="reg"]', './orgName[@type="reg"]']
            filter: 'get_full_name'

  places:
    xpath: '//*:TEI[@*:doctype="register"]//*:listPlace//*:place'
    properties:
      name:
        properties:
          toponym:
            xpath: ['./placeName']
      geonamesUri: 
        xpath: ['./idno']
      type:
        xpath: ['.']
        attrib: ['type']

  works:
    xpath: '//*:TEI[@*:doctype="register"]//*:listBibl//*:bibl'
    properties:
      title:
        xpath: ['./title']
      type: 
        xpath: ['.']
        attrib: ['type']

