FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-2025-02-10

WORKDIR /app

RUN pip install poetry lxml snakesist python-dotenv diskcache

COPY ./pyproject.toml ./poetry.lock* ./

RUN poetry install --no-root

COPY . .
# COPY .env.production .env
